import { writeFileSync } from 'fs';
import { join } from 'path';
import type { Goal, SubTask, Worker } from './types.js';
import { getGoal, getSubTasksByGoal } from './db.js';

export function generateReport(goalId: string, workers: Worker[], reportsDir: string): string {
  const goal = getGoal(goalId);
  if (!goal) throw new Error(`Goal ${goalId} not found`);

  const subTasks = getSubTasksByGoal(goalId);
  const report = buildMarkdownReport(goal, subTasks, workers);

  const reportPath = join(reportsDir, `${goalId}_report.md`);
  writeFileSync(reportPath, report);

  return reportPath;
}

function buildMarkdownReport(goal: Goal, subTasks: SubTask[], workers: Worker[]): string {
  const completed = subTasks.filter(st => st.status === 'completed').length;
  const failed = subTasks.filter(st => st.status === 'failed').length;
  const totalTurns = workers.reduce((sum, w) => sum + w.stats.turnsUsed, 0);
  const totalFiles = new Set(workers.flatMap(w => w.stats.filesModified)).size;

  const duration = goal.completedAt
    ? formatDuration(new Date(goal.createdAt), new Date(goal.completedAt))
    : 'In progress';

  return `# Goal Report: ${goal.id}

## Overview
- **Description**: ${goal.description}
- **Work Directory**: ${goal.workDir}
- **Priority**: ${goal.priority}
- **Status**: ${goal.status}
- **Duration**: ${duration}
- **Created**: ${goal.createdAt}
- **Completed**: ${goal.completedAt || 'N/A'}

## Summary
| Metric | Value |
|--------|-------|
| Subtasks | ${subTasks.length} |
| Completed | ${completed} |
| Failed | ${failed} |
| Workers | ${workers.length} |
| Total Turns | ${totalTurns} |
| Files Modified | ${totalFiles} |

## Subtasks
${subTasks.map(st => `
### ${st.title} (${st.status})
- **Role**: ${st.role}
- **Description**: ${st.description.slice(0, 200)}${st.description.length > 200 ? '...' : ''}
- **Assigned Worker**: ${st.assignedWorkerId || 'Unassigned'}
- **Started**: ${st.startedAt || 'N/A'}
- **Completed**: ${st.completedAt || 'N/A'}
${st.result ? `
**Result**: ${st.result.success ? '✅ Success' : '❌ Failed'}
${st.result.output ? `\n\`\`\`\n${st.result.output.slice(0, 500)}\n\`\`\`` : ''}
${st.result.filesModified.length > 0 ? `\n**Files Modified**: ${st.result.filesModified.join(', ')}` : ''}
` : ''}
`).join('')}

## Workers
${workers.map(w => `
### ${w.id} (${w.status})
- **Role**: ${w.role}
- **PID**: ${w.pid}
- **Turns Used**: ${w.stats.turnsUsed}
- **Errors**: ${w.stats.errors}
- **Files Modified**: ${w.stats.filesModified.length}
- **Tools Used**: ${Object.entries(w.stats.toolsUsed).map(([k, v]) => `${k}(${v})`).join(', ') || 'None'}
`).join('')}

---
*Generated by CC Orchestrator at ${new Date().toISOString()}*
`;
}

function formatDuration(start: Date, end: Date): string {
  const ms = end.getTime() - start.getTime();
  const hours = Math.floor(ms / (1000 * 60 * 60));
  const minutes = Math.floor((ms % (1000 * 60 * 60)) / (1000 * 60));
  if (hours > 0) return `${hours}h ${minutes}m`;
  return `${minutes}m`;
}
